### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by turtlekazu** [turtlekazu/furima-34437#10]
# URL
https://furima-34437.herokuapp.com/

# Basic認証のIDとパスワード
- id: turtle
- pw: 9876 

# 出品者用のメールアドレスとパスワード
- mail: furima@tarou
- pw: furima1234

# 購入者用のメールアドレスとパスワード
- mail: furima@jirou
- pw: furima2345

**Comment by turtlekazu** [comment]
お世話になっております。
フリマアプリを一通り実装完了いたしました。お手数ですが、挙動確認をどうぞよろしくお願いいたします！

**Comment by naru6117** [comment]
@turtlekazu さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　**LGTMです✨　
おめでとうございます🎉**
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

![最終課題終了_おめでとう画像3](https://user-images.githubusercontent.com/49669977/109447759-bcb3b680-7a87-11eb-81cd-5fed4046e39a.png)


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**

**Comment by turtlekazu** [comment]
挙動確認いただき、LGTMとのこと誠にありがとうございます！
オリジナルアプリ開発でも気を抜かずに、学んだ知識を総動員させて頑張っていきたいと思います。今後ともどうぞよろしくお願いいたします！
